version: "3.9"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=light-system-db
    volumes:
      - polls_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - polls_redis_data:/bitnami/redis/data

  app:
    build: .
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "3333:3333"
    command: npm run dev

volumes:
  polls_pg_data:
  polls_redis_data:
